name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main
  release:
    types: [published]

env:
  INTERPRETER: '3.11'
  RUSTFLAGS: -C debuginfo=0

jobs:

  build:
    name: build - ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip

          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            archive: tar.gz

          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            archive: tar.xz

          - os: macos-latest
            target: x86_64-apple-darwin
            archive: zip

          - os: macos-latest
            target: aarch64-apple-darwin
            archive: zip

    env:
      TARGET: ${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        run: |
              rustup override set stable
              rustup update
              rustup target add ${{ matrix.target }}
              rustup component add rust-src
              

      - name: Update apt repositories
        if: contains(matrix.os, 'ubuntu')
        run: |
            sudo apt-get update -y
            sudo apt-get install

      - name: Build binaries
        run: cargo build --release --target ${{ matrix.target }}

      - name: Zip Windows binaries
        if: contains(matrix.archive, 'zip') && contains(matrix.os, 'windows')
        run: Compress-Archive ./target/release/ scouter-server-${{ matrix.target }}.zip

      - name: Zip MacOS binaries
        if: contains(matrix.archive, 'zip') && contains(matrix.os, 'macos')
        run: zip -r scouter-server-${{ matrix.target }}.zip ./target/release/

      - name: gzip binaries
        if: contains(matrix.archive, 'tar.gz')
        run: tar -czf scouter-server-${{ matrix.target }}.tar.gz ./target/release/

      - name: xz binaries
        if: contains(matrix.archive, 'tar.xz')
        run: tar -cJf scouter-server-${{ matrix.target }}.tar.xz ./target/release/

      - uses: actions/upload-artifact@v4
        with:
          name: scouter-server-${{ matrix.target }}.${{matrix.archive}}
          path: scouter-server-${{ matrix.target }}.${{matrix.archive}}

  release-binary-assets:
    if: github.event_name == 'release'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: get dist artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: scouter-server-*
          path: dist

      - name: list dist files
        run: |
         ls -lhR dist
         echo "`ls dist | wc -l` files"

      - name: Upload files to release tag
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
        run: |
          for file in dist/*; do
            echo "Uploading $file"
            gh release upload ${{ github.event.release.name }} $file
          done

     


