name: Release-binary

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

env:
  INTERPRETER: '3.11'
  RUSTFLAGS: -C debuginfo=0

jobs:
    

  build-ubuntu:
    name: build - ubuntu - ${{ matrix.manylinux }} - ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
        manylinux: [auto]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup override set stable && rustup update

      - name: Build binary
        run: cargo build --release
