name: Release-binary

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

env:
  INTERPRETER: '3.11'
  RUSTFLAGS: -C debuginfo=0

jobs:
    

  build-ubuntu:
    name: build - ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, aarch64-apple-darwin, x86_64-pc-windows-gnu]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
              rustup override set stable
              rustup update
              rustup target add ${{ matrix.target }}

      - name: Build binary
        run: |
            cargo build --release --target ${{ matrix.target }}
