
name: Lints-Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test-os:
    name: test ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup override set stable && rustup update

      - name: Install clippy
        run: rustup component add clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Start kafka and postgres
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Wait for kafka until it is ready
        run: |
          while ! docker exec scouter_server_kafka kafka-topics --bootstrap-server kafka:29092 --list; do
            sleep 5
          done

      - name: Wait for postgres until it is ready
        run: |
          while ! docker exec scouter_server_db pg_isready -U postgres; do
            sleep 5
          done
          
      - name: Test
        run: cargo test -- --nocapture  --test-threads=1
        env:
          RUST_BACKTRACE: 1

      - name: Bench
        run: cargo bench
        env:
          RUST_BACKTRACE: 1

      - name: Stop Containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down