
name: Lints-Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test-os:
    name: test ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup override set stable && rustup update

      - name: Install clippy
        run: rustup component add clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
          
      - name: Test
        run: ./tests/run_tests.sh
        env:
          RUST_BACKTRACE: 1
          KAFKA_BROKER: localhost:9092
          KAFKA_TOPIC: scouter_monitoring
          KAFKA_GROUP: scouter
          DATABASE_URL: postgresql://postgres:admin@localhost:5432/monitor?
